### ISSUE TITLE
Devuan/Debianb packaging etc

### ISSUE THREAD

**Issue by klink-mit-panzerslip** [the-djmaze/snappymail#185]
Hello,

I am using rainloop since years and am a bit annoyed by the fact is seem under-maintained (security issues posted with no reply).

I would switch to snappymail but it would be more practical if it was submitted to Devuan (through Debian).

Regards,

**Comment by the-djmaze** [comment]
Yes, RainLoop development is slow. That is why i forked it.
However, due to the current fast development of SnappyMail, i understand nobody has made Debian releases as of yet.

Because every 1-2 weeks i release a new version with improvements, bugfixes but also new bugs.

And thanks to everyone here it does improve and almost is up to date with latest RFC's.
Then the release cycle can slow down and be considered stable enough for larger distro's and someone might pick it up to maintain.

So for now you're on your own as i don't have distr channels yet.

**Comment by the-djmaze** [comment]
Could you test the v2.13.0 .deb i created?

**Comment by yeupou** [comment]
Hi there,

I tested the 2.13.0 .deb

Minor issue:

- the symlinks created on the postinst (/etc/apache2/sites-available/snappymail.conf etc) test  only if the source file exists, if the destination already exists (like in my case since I was doing test) the postinst cannot be completed 
- more on that: should these symlinks even be created? It because activate software just on install and I am not sure that it is the recommended practice. Do other packages provide a sites-enabled symlink in addition to the automated symlink to sites-enabled


Blocker issues:

- files are installed in /usr/share/snappymail/snappymail/v/0.0.0/ instead of /usr/share/snappymail/snappymail/v/2.13.1/ so nothing works until you create a symlink
- once done, it stills fails, with "[202] Data folder permissions error [mkdir]" and, in logs:
`-2022/02/28 21:37:00 [error] 5103#5103: *13 FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): Permission denied in /usr/share/snappymail/snappymail/v/0.0.0/setup.php on line 87" while reading response header from upstream, client: 83.159.142.158, server: ~^mx, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", `
- files in /var/lib/snappymail belongs to www-data and /usr/share/snappymail/snappymail/v/0.0.0 to root so that should be fine

To which point I upgraded using my own dirty package. I am sure it is a trivial issue, maybe related to the 0.0.0 path or else.
With my dirty package  (simple download of the package https://gitlab.com/yeupou/rien/-/blob/master/webmail-snappymail/usr/local/share/get-snappymail.sh + dedicated include.php, then packaged in an crude automated way), which resultsin something similar (in terms of files locations, except the code itself is in /usr/local instead of /usr), it worked, with the same /var/lib/_data_ folder.



Question:

- are you sure about the dependencies? on my own package based on the requirements, I have:
Depends: php-redis, php-zip, php-uuid, php-imagick, php-apcu

**Comment by the-djmaze** [comment]
@yeupou thanks for testing!

> Minor issue:
> 
>     * the symlinks created on the postinst (/etc/apache2/sites-available/snappymail.conf etc) test  only if the source file exists, if the destination already exists (like in my case since I was doing test) the postinst cannot be completed
>     * more on that: should these symlinks even be created? It activates software just on install and I am not sure that it is the recommended practice. Do other packages provide a sites-enabled symlink in addition to the automated symlink to sites-enabled

Shouldn't be there. It was in my testcode of `postinst` which is not in git. Removed it.

> Blocker issues:
> 
>     * files are installed in /usr/share/snappymail/snappymail/v/0.0.0/ instead of /usr/share/snappymail/snappymail/v/2.13.1/ so nothing works until you create a symlink
> 

Changed that.

>     * once done, it stills fails, with "[202] Data folder permissions error [mkdir]" and, in logs:
>       `-2022/02/28 21:37:00 [error] 5103#5103: *13 FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): Permission denied in /usr/share/snappymail/snappymail/v/0.0.0/setup.php on line 87" while reading response header from upstream, client: 83.159.xxx.xxx, server: ~^mx, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", `

Odd, i've added error_log() entry with full path.
Maybe there's a bug in the include.php for `APP_DATA_FOLDER_PATH`

> Question:
> 
>     * are you sure about the dependencies? on my own package based on the requirements, I have:
>       Depends: php-redis, php-zip, php-uuid, php-imagick, php-apcu
> 

The only required dependencies are:
* php-mbstring
* php-zlib
* php-json (should be enabled by default)
* php-libxml (should be enabled by default)
* php-dom (should be enabled by default)
* nginx | apache2 | httpd
* php-fpm | libapache2-mod-php

Optional dependencies are:
* php-sqlite3 | php-mysql | php-pgsql (for contacts)
* php-curl
* php-exif
* php-gnupg
* php-gd
* php-gmagick
* php-imagick
* php-intl
* php-ldap
* php-openssl
* php-pdo_mysql
* php-pdo_pgsql
* php-redis
* php-sodium
* php-pdo_sqlite
* php-uuid
* php-xxtea
* php-zip

**Comment by yeupou** [comment]
Regarding the dependencies, I think you could use Recommends vs Suggests at least to put php-sodium in Recommends (along with any package that provides features, if you do not want to put them directly as depends, which can be a legitimate packaging choice too) and the other two as in Suggests.


Regarding the privileges issue, not sure how it should work.
As far I understand, it fails trying to mkdir( $sCheckFolder) while $sCheckFolder =  APP_DATA_FOLDER_PATH.$sCheckName; $sCheckName = 'delete_if_you_see_it_after_install'

So it would try to mkdir(APP_DATA_FOLDER_PATH.delete_if_you_see_it_after_install)

Considering that APP_DATA_FOLDER_PATH is set by the /usr/share/snappymail/include.php it should work out of the box

Note however that in my own /usr/local/share/snappymail/include.php I have:
```
<?php
define('APP_DATA_FOLDER_PATH', '/var/lib/snappymail/');
```
So it means mkdir("/var/lib/snappymail/delete_if_you_see_it_after_install")
I do not remember how it was in your, but it would fail if the last slash was missing because it would result in mkdir("/var/lib/snappymaildelete_if_you_see_it_after_install") while /var/lib should be 0755 root:root owned.

There is already a is_dir test on APP_DATA_FOLDER_PATH. Maybe, if there is no trailing slash, it should be forcefully added. Or you can simply change line 53-54 to
```
$sCheckFolder = APP_DATA_FOLDER_PATH.'/'.$sCheckName;
$sCheckFilePath = sCheckFolder.'/'.$sCheckName.'.file';
```
(since the extra the trailing slash would be harmless in  /var/lib/snappymail//delete_if_you_see_it_after_install)

**Comment by the-djmaze** [comment]
> I think you could use Recommends vs Suggests at least to put php-sodium in Recommends

Made some changes to the `control` file.

**Comment by yeupou** [comment]
No problem with 2.13.2. Great!

Next step would be creating a repository, some folder with a Packages file containing

```
Package: snappymail
Architecture: all
Version: 2.13.2
Maintainer: SnappyMail <debian@snappymail.eu>
Depends: nginx | apache2 | httpd, php-fpm | libapache2-mod-php, php-json, php-mbstring
Recommends: php-intl, php-sodium, php-uuid
Suggests: php-sqlite3 | php-mysql | php-pgsql, php-curl, php-exif, php-gnupg, php-gd | php-gmagick | php-imagick, p
hp-openssl, php-zip
Filename: ./snappymail_2.13.2-1_all.deb
Size: 2831352
MD5sum: 093e37b03a66252769f98b66ae364ef3
SHA1: 761b1ae89c1381d6a0fefe39503b094408a13801
SHA256: ac5c3a0010cda7bbe4ac7e8cb5e5a9f03acacfaec4cff020c5c80543c7cb8fd9
SHA512: a35ad444926def6fc8f9dfce6e26962a1a68b7fdffbd55df2667fe1958634da6cb1acd190683d80568c58727cbfc541adf099fa2877
5f0d5085f8147b1705f44
Homepage: https://snappymail.eu
Description: SnappyMail is a PHP-based simple, modern, lightweight & fast web-based email client with no database r
equirements.
 It supports IMAP, SMTP and Sieve protocols, multiple accounts and identities, an admin panel for configuration.
 Plugins can be installed to further extend functionality.
 Emails are not stored locally, but are accessed through IMAP.
Vcs-Browser: https://github.com/the-djmaze/snappymail
Vcs-Git: https://github.com/the-djmaze/snappymail.git
```

as written by: 
```
apt-ftparchive packages . > Packages 
apt-ftparchive release . > Release
gpg $(GPG_SIGNATURES) --digest-algo SHA512 --clearsign --output InRelease Release
gpg $(GPG_SIGNATURES) --digest-algo SHA512 -abs --output Release.gpg Release
```

along with a snappymail-keyring package with relevant keys in /etc/apt/trusted.gpg.d/snappymail.gpg (and possibly, for conveniency, a /etc/apt/sources.list.d/snappymail.list).

**Comment by jh23453** [comment]
I had installed snappymail manually with apache2 configuration in /etc/apache2-webmail/. 
I've installed snappymail_2.13.2-1_all.deb on Debian 11. I expected to get a file in /etc/apache2/sites-available, but there is none.
For now I've modified my former configuration (changed paths) and snappymail seems to work for now.
Thanks a lot!

**Comment by the-djmaze** [comment]
> Next step would be creating a repository,

Does this work for you?
https://snappymail.eu/repository/deb/

**Comment by yeupou** [comment]
To test the repository, I would require the GPG key

```
Err:3 https://snappymail.eu/repository/deb ./ InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 48208BA13290F3EB
```
(well I could run it with --allow-unauthenticated)
https://wiki.debian.org/SecureApt#How_apt_uses_Release.gpg

**Comment by yeupou** [comment]
I tested with  apt -o Acquire::AllowInsecureRepositories=true update but it fails.

In Packages, you have a full path like /home/djmaze/public_html/mhx/whm/snappymail/build/dist/releases/webmail/2.13.4/snappymail_2.13.4-1_all.deb that may be the problem. 
I would expect  a relative path related to webroot or something like that.

**Comment by the-djmaze** [comment]
> I would require the GPG key

It's at several places:
* https://keyserver.ubuntu.com Hockeypuck OpenPGP keyserver
* https://snappymail.eu/repository/deb/48208BA13290F3EB.asc
* https://github.com/the-djmaze/snappymail/blob/master/build/SnappyMail.asc


> I would expect a relative path related to webroot or something like that.

I've fixed that. You can try again.

**Comment by yeupou** [comment]
for the key, I did:
```
gpg --keyserver keyserver.ubuntu.com --recv-keys   48208BA13290F3EB
gpg -a --export 48208BA13290F3EB | apt-key add -
```

However, I still have a problem
`W: Skipping acquire of configured file 'Packages' as repository 'https://snappymail.eu/repository/deb ./ InRelease' does not seem to provide it (sources.list entry misspelt?)`

What do you recommend as source.list entry? I have
 `deb https://snappymail.eu/repository/deb ./`
which make InRelease being loaded but failing to provide the relevant Packages file.

**Comment by the-djmaze** [comment]
@yeupou i only had a `Packages.gz`, so i've added the `Packages`

**Comment by yeupou** [comment]
It worked!

**Comment by ser** [comment]
I just want to signal that ` deb https://snappymail.eu/repository/deb ./` is not documented anywhere so it took me a while to find out the correct syntax.

**Comment by matthys70** [comment]
Where to find /etc/apache2/sites-available/snappymail.conf in debian package? Seem not be installed ... and NOT included in package :-(

**Comment by rolfen** [comment]
I installed the package and then how am I supposed to know where the www root is so that I can properly add and configure a nginx virtual host?

Please mention it somewhere.

**Comment by matthys70** [comment]
Just to get you started, this is my snappymail.conf in apache:

```
# Those aliases do not work properly with several hosts on your apache server
# Uncomment them to use it or adapt them to your configuration
Alias /snappymail /usr/share/snappymail

<Directory /usr/share/snappymail>
  DirectoryIndex index.php
  Options -Indexes +ExecCGI
  AllowOverride All
  Order deny,allow
  Allow from all
  Require all granted
</Directory>

<Directory /var/lib/snappymail>
  Options -Indexes
  Deny from all
</Directory>
```

**Comment by gerstavros** [comment]
I don't see anywhere a readme for installation from repository for debian. and because probably lots of people are searching for this, and find multiple scattered information, i summarize here the way to use the repo

Firstly we install the repo key 
`wget -qO - https://snappymail.eu/repository/deb/48208BA13290F3EB.asc | gpg --dearmor -o /usr/share/keyrings/snappymail.gpg`
Then we add the repo
`echo "deb [signed-by=/usr/share/keyrings/snappymail.gpg] https://snappymail.eu/repository/deb/ ./" | tee /etc/apt/sources.list.d/snappymail.list`
Then we update apt database
`apt update`
and we install snappymail
`apt install snappymail`

Snappymail is now installed on  /usr/share/snappymail, so we use this folder for the apache/nginx or else vhost settings, or we link it to our vhost home folder.

**Comment by wisc7** [comment]
Update: 29 June 2025- got it working - will try to update the below for the additional steps and configurations needed...

original post
@gerstavros 
when you say "use this folder for the apache/nginx"
that would mean the following?

nano /etc/nginx/sites-enabled/default
change 
        root /var/www/html;
to
        root /usr/share/snappymail;

or adding links to the directory /usr/share/snappymail 
EG:
 ln /usr/share/snappymail/ /var/www/html/snappymail -s

once this is done, you get:
403 Forbidden
nginx/1.22.1

I see based on the instructions page that we would also need to run this:

find /var/www/webmail/snappymail -type d -exec chmod 755 {} \\;
find /var/www/webmail/snappymail -type f -exec chmod 644 {} \\;
chown -R www-data:www-data /var/www/webmail/snappymail

(or update the permissions on the /usr/share/snappymail folder)

The 403 error is also because its trying to list the directory... seems by default ngnix doesnt enable PHP, so that's another thing to enable via the config files. 

(or more to the point, we need to use the "Webserver configuration - Nginx" from the main install page instead of the one that comes with this install.)

slight detour - need to install:
sudo apt-get install php-xml
(for DOM extension for PHP)

continued in the next post below

(side note: perhaps more info on
https://github.com/the-djmaze/snappymail/wiki/Installation-instructions for this Debian install to assist with configuring nginx)

**Comment by wisc7** [comment]
~~Tried to modify the default site configuration file IE these parts:~~

```
        # Add index.php to the list if you are using PHP
!!        index index.html index.htm index.nginx-debian.html index.php;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
!!                try_files $uri  =404;
                #try_files $uri $uri/ =404;
        }

        # pass PHP scripts to FastCGI server

!!        location ~ \.php$ {
!!                include snippets/fastcgi-php.conf;

                # With php-fpm (or other unix sockets):
#                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
!!                 fastcgi_pass unix:/run/php/php8.2-fpm.sock;
                # With php-cgi (or other tcp sockets):

```

~~modified lines with !!
however still getting the following in the access logs as they dont exist:~~

important note, if you want to use lets encrypt as per
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-debian-11

you will need to do this when ngnix is configured correctly and able to run, (IE before you swap over the configuration file - or the next step), as once you enable SSL, ngnix will need the pem and key files before it will load up/service start again.

<once you have your lets encrypt certificates - or if you want to use a self signed certificate for now>

get the "Webserver configuration Nginx" configuration file from:
https://github.com/the-djmaze/snappymail/wiki/Installation-instructions

and overwrote the default site configuration file:

IE
/etc/nginx/sites-enabled/default

the "Webserver configuration Nginx", require setting up Letsencrypt or other certificates for SSH....
eg:
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-debian-11

from above digitalocean link- install cert bot:
sudo apt install certbot python3-certbot-nginx

you can then run through the rest of the document or use the following to use a self signed certificate for testing:
<reiterating from above - it is important to note that when the configuration file has been modified from the default, ngnix wont start without certificates, so you would have to do this before using the snappy mail configuration file) 

modify web configuration file:
> nano /etc/nginx/sites-enabled/default

set "server_name" to your server name (in the main script example this is set to "webmail.example.com"
set ssl_certificate and ssl_certificate_key to a location somewhere. 

IE - These lines
ssl_certificate /etc/letsencrypt/live/webmail.example.com/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/webmail.example.com/privkey.pem;


set the home directory for snappy mail here:
        ###
        # Define the document root
        root /var/www/webmail/snappymail;


then create a self signed certificate for testing.

\# Generate a private key
openssl genrsa -out example.key 2048

\# Generate a CSR (Certificate Signing Request)
openssl req -new -key example.key -out example.csr

\# Self-sign the certificate using the private key
openssl x509 -req -days 365 -in example.csr -signkey example.key -out example.crt

\# Combine the private key and certificate into a single PEM file
cat example.key example.crt > example.pem

\# (Optional) Restrict permissions on the private key
chmod 400 example.key

move the key and pem file to the folder you pointed to above eg:
/etc/letsencrypt/live/webmail.example.com/
and rename to fullchain.pem; and key file to privkey.pem; (or whatever you changed them to above)

then you should be able to start the server 

when trying to access the server via https://<server>/?admin
502 Bad Gateway

to overcome, modified config file again:
> nano /etc/nginx/sites-enabled/default

change the last section to
```
        location ~* \.php$ {
#               fastcgi_pass    unix:/run/php-fpm.sock;
                fastcgi_pass    unix:/run/php/php8.2-fpm.sock;
                include         fastcgi_params;
                fastcgi_param   SCRIPT_FILENAME    $document_root$fastcgi_script_name;
                fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
        }
```

eg added comment to blank out the "fastcgi_pass" line, then added :
 fastcgi_pass    unix:/run/php/php8.2-fpm.sock;
in its place... this will point to the current PHP version 
(may require updating for your PHP version)
you can get your current version by running this command:
systemctl list-units "php*-fpm*"

then finally, you should be able to get to the admin console and be able to log in following the instructions on the main page.

sorry for the above, its a bit messed up, as i was writing it as working it out... If i create another snappy mail server, I'll provide a step by step guide including all of the configurations. 

Other useful commands:
ngnix check configuration files are valid:
nginx -t

restart ngnix
 service nginx restart

Review ngnix tail webserver error logs: - run this if you have errors when trying to connect to the server
tail /var/log/nginx/error.log

get first login password: (from snappymail home directory - after bringing up the homepage for the first time)
cat ./data/_data_/_default_/admin_password.txt

(my default was "/var/lib/snappymail/_data_/_default_/admin_password.txt"
you can find this in the include file:
cat /var/www/html/snappymail/include.php
)



Modify default website for ngnix (can use this for snappy mail) 
nano /etc/nginx/sites-enabled/default

ngnix service logs
journalctl -xeu nginx.service

**Comment by abcnorio** [comment]
Hello,

using v 2.38.2 I can log into the admin using the .../?admin URL which works - domain access test with a user that exists on a local imap works, but not log in with the same user using full mail address like user@domain.xx:

```
authentification failure
Server-message: InvalidInputArgument[903]
```

Anything else to do to add ie. use an account?
Where do I get a log entry? nginx is not helpful here. In the config added

`/var/log/snappylog`

and gave perms to `www-data` for that folder. No entry. Thanks!

**Comment by wisc7** [comment]
\# Full latest updated instructions - without all the crud.

\# pre requisits 
sudo apt install gnupg php-xml -y

\# start with the debian specific install on the main page: https://github.com/the-djmaze/snappymail/wiki/Installation-instructions (as follows) - and as per above from @gerstavros

mkdir -p /usr/share/keyrings/
wget -O- https://snappymail.eu/repository/deb/48208BA13290F3EB.asc | gpg --dearmor > /usr/share/keyrings/snappymail.gpg

\# Create /etc/apt/sources.list.d/snappymail.list with following line.
echo "deb [signed-by=/usr/share/keyrings/snappymail.gpg] https://snappymail.eu/repository/deb ./" > /etc/apt/sources.list.d/snappymail.list

/# now install snappymail from the repository we just added.
apt update
apt install snappymaily

\# snappyail is now installed, next move to the general instructions on https://github.com/the-djmaze/snappymail/wiki/Installation-instructions (as follows with updated paths)

\# create a symbolic link between the install files and the web directory
ln /usr/share/snappymail/ /var/www/html/snappymail -s

\# set permissions (unsure if these 3 lines are required give we are using a symbolic link)
find /var/www/html/snappymail -type d -exec chmod 755 {} \;
find /var/www/html/snappymail -type f -exec chmod 644 {} \;
chown -R www-data:www-data /var/www/html/snappymail

\# (I also ran this in my latest install - above may not be required)
find //usr/share/snappymail/ -type d -exec chmod 755 {} \;
find /usr/share/snappymail/ -type f -exec chmod 644 {} \;
chown -R www-data:www-data /usr/share/snappymail/ 

\# Then run the following to get your PHP version - note id down for the later step
systemctl list-units "php*-fpm*"

\# backup website config to home directory
cp /etc/nginx/sites-enabled/default ~/default.web.bak

\#  see above for notes on generating a server cert. (via lets encrypt or self signed)

\# then modify /etc/nginx/sites-enabled/default
nano /etc/nginx/sites-enabled/default

\# 1. get the Nginx config from https://github.com/the-djmaze/snappymail/wiki/Installation-instructions and dump it over your defaul file "/etc/nginx/sites-enabled/default"
\# fill in the domain name and SSL cert locations
\# IE ssl_certificate, ssl_certificate, and ssl_certificate

\# 2. set the home directory for snappy mail here: IE update this bit:

\###
\# Define the document root

root /var/www/html/snappymail;

\# 3. find this section "        # Last but not least, the PHP-FPM settings"
\# set  "fastcgi_pass    unix:/run/php-fpm.sock;"  to "                fastcgi_pass    unix:/run/php/php\<version from the above command\>-fpm.sock;"

\# 4. save and exit

\# restart ngnix
service nginx restart

\# point your browser to the newly created server

https://<Ip/domainnmame>/?admin

\# use the password in the following file to access. (note the underscores may be trimmed by git comments)  ( documentation states "cat ./data/data/default/admin_password.txt"
cat /var/lib/snappymail/\_data\_/\_default\_/admin_password.txt

**Comment by abcnorio** [comment]
Thanks, will try that out!
