### ISSUE TITLE
[Nextcloud] Login with Nextcloud username not possible

### ISSUE THREAD

**Issue by cm-schl** [the-djmaze/snappymail#596]
**Describe the bug**
After updating to SnappyMail v2.19.4 it seems not possible to login by using the Nextcloud username (by choosing in the Nextcloud settings -> Additional settings -> Attempt to automatically login users with their Nextcloud username and password, or user-defined credentials, if set.

In fact the log complains about a not complete mail address - this is true because we're using the username to login. Prior to the update the login by username & password was possible without problems.

**To Reproduce**
Simply set login method to "Attempt to automatically login users with their Nextcloud username and password, or user-defined credentials, if set." and try to open SnappyMail in Nextcloud.
The login dialog is shown instead of entering to SnappyMail.

Trying to use username and password manually at the login prompt does not works either.

**Expected behavior**
Automatic login like before v2.19.4

**Please complete the following information:**
- Browser: Firefox 102.4.0esr
- IMAP daemon: cyrus
- PHP version: 8.0.24
- SnappyMail Version: v2.19.4

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
The log contains the following info:

```
LOGIN[INFO]: The email address "<NEXTCLOUD USERNAME>" is not complete
LOGIN[INFO]: Default domain not configured.
```

**Comment by BiglifeMatt** [comment]
After the upgrade I just get a pop up window with "ERROR: Undefined class constant 'AUTOLOGOUT'"

**Comment by the-djmaze** [comment]
Correct, issue is the old plugin.
Because there was another issue with it #570

**Comment by the-djmaze** [comment]
Login with only `name` is possible.
1. Admin -> Config -> default_domain
If someone logs in without "@domain.tld", this value will be used
When this value is HTTP_HOST, the $_SERVER["HTTP_HOST"] value is used.
When this value is SERVER_NAME, the $_SERVER["SERVER_NAME"] value is used.
When this value is gethostname, the gethostname() value is used.
2. Admin -> Domains
Have a domain matching the default_domain or * (wildcard) and configure.

**Comment by the-djmaze** [comment]
Now i think about it.
What if it will auto-create a default_domain `nextcloud` and a domain `nextcloud`.

Would that be enough?

**Comment by MI-KY** [comment]
When you configure Nextcloud to get the users from an LDAP and your mailserver only accepts logins with the LDAP username then there is no domain you could add to the username... In such a case the domain has to retrieved from the mailaddress of the nextcloud user (=the address of the user in LDAP)...

Somehow the login with nextcloud username also worked for me before the update.

**Comment by the-djmaze** [comment]
I'm testing changes and investigating this issue

**Comment by the-djmaze** [comment]
I've released 2.19.5 it might solve the issue.
Go to Nextcloud settings -> admin -> additional
Then go to the SnappyMail admin and see the new Domains -> nextcloud

**Comment by rainerzufall** [comment]
2.19.5 solved the issue for me! did not do anything in admin settings, just installed 2.19.5 and am able to login in normally.

**Comment by cm-schl** [comment]
@the-djmaze 
Sorry, I couldn't test this until now. Unfortunately also with v2.19.7 the problem persists - using the configuration described in my first post the users gets to see the login prompt. Also a manual login fails.

I think the solution by adding a default domain "nextcloud" does not work in my case - it points to localhost where no IMAP server can be found... Also I've already had a working domain configuration.

So configured a default domain and looked again into the logs (removed username and domain):

```
[2022-11-03 11:11:19.385][30d03549] LOGIN[INFO]: The email address "USERNAME" is not complete
[2022-11-03 11:11:19.385][30d03549] LOGIN[INFO]: Default domain "example.com" was used. (USERNAME > USERNAME@example.com)
[2022-11-03 11:11:19.386][30d03549] IMAP[INFO]: Start connection to "tcp://imap.example.com:143"
[2022-11-03 11:11:19.393][30d03549] IMAP[INFO]: Connect (success)
```
so after introducing the "default domain" Snappymail always adds a domain to the username. This is a bit misleading as in Nextcloud the option says "Attempt to automatically login users with their Nextcloud username and password, or user-defined credentials, if set". IMO in this case it should use only the username - not \<username\>@\<default-domain\>.

So I looked into the domain configuration in the Snappymail Admin Interface and there you can activate "use short logins". After activating this the login for the users work.

I see the use case for the "default domain" - but in this specific case it's really irritating: you choose to login with the Nextcloud username -> Snappymail adds the chosen default domain -> the domain config itself removes the domain to use only the part before the @ to login...

**Comment by the-djmaze** [comment]
Ah yes, i should write some documentation about it.

To send an email you need a valid email address like `john@example.com`.
SnappyMail stores data in a directory, based on that in `/example.com/john/`.

Most webmail systems use a login name as `john@example.com` but there are other cases.
For example they also use system login names or other.

In that case your login is just `john` but then SnappyMail has no idea which email address to use for `john` because the MX server stores emails to `john@example.com` in the `john` account.

That is why SnappyMail requires a few things to get the `john` login working in a way that it can also send messages in behalf of `john@example.com` and store the settings properly in `/example.com/john/`.

Here is where the "default domain" setting comes to play.
It will add a domain to `john` so it knows enough to also send emails and store settings.

Then the second part is the login part. Based on IMAP server configuration you login with `john@example.com` or `john` and that is the "use short logins" setting.

I also use a different approach.
My system users can have a mailbox or not. The way i validate that is: `user@hostname`
So the login on IMAP is `user@hostname`.
However, in SnappyMail they can just login as `user`.
The system will use `default_domain = hostname` so the login becomes `user@hostname`.
In this case "use short logins" is off.

**Comment by cm-schl** [comment]
Thanks for this information!

If you would like I could try to help regarding some documentation. If you maybe choose which solution you would you like to use (Github Wiki, Read the Docs, ecc.) and maybe define some structure i could try to add some information 🙂.

**Comment by the-djmaze** [comment]
Great!
Currently the Wiki here is used.
