### ISSUE TITLE
Searching on Nextcloud search

### ISSUE THREAD

**Issue by chrisdent** [the-djmaze/snappymail#787]
While searching on Nextcloud search this message appears:

An error occurred while searching for SnappyMail

V. 2.23.1

**Comment by the-djmaze** [comment]
Duplicate of #777

**Comment by daffydock** [comment]
Worth nothing that I too get that error but that I do not have the Fulltextsearch app active, or even installed. I do not think it is a duplicate. 

Upon doing a search, log shows the following error as well:

Exception: Typed property MailSo\Mail\MessageListParams::$bUseThreads must not be accessed before initialization in file '/home/YYYY/XXXX.ZZZZZZ.com/apps/snappymail/app/snappymail/v/2.24.3/app/libraries/MailSo/Mail/MailClient.php' line 643

Goes without saying that if I disable Snappymail or if simply I do not do any searches that the error disappears or does get prompted. 

This aside, Happy Holidays.

**Comment by airesch** [comment]
Confirming, I have the same problem as @daffydock 

Nextcloud 25.0.2 running in a docker, SnappyMail 2.24.3, Nextcloud Integration extension 2.13, whenever I do a search I get the error popup and the below in my log:

Exception: Typed property MailSo\Mail\MessageListParams::$bUseThreads must not be accessed before initialization in file '/var/www/html/custom_apps/snappymail/app/snappymail/v/2.24.3/app/libraries/MailSo/Mail/MailClient.php' line 643

**Comment by daffydock** [comment]
Updated to 2.24.2
Checked search, log off and logged on. Checked again. 

Error is fixed. Thank you, @the-djmaze. 

I wish a Happy New Year's and a great 2023!

**Comment by elhananjair** [comment]
@daffydock @the-djmaze  am still facing this issue though
[Kooha-2023-01-01-14-18-09.webm](https://user-images.githubusercontent.com/69236638/210169114-a6574ada-ea50-4bf5-bfac-5ca866578a99.webm)

**Comment by Silberlog** [comment]
Search still doesn't work for us, facing the following exception in nextcloud.log : 

{"reqId":"Y7XIMktY4Fb90auGc2NoxgAAAIo","level":3,"time":"2023-01-04T18:40:50+00:00","remoteAddr":"192.168.1.254","user":"thomas","app":"no app in context","method":"GET","url":"/ocs/v2.php/search/providers/snappymail/search?term=ama&from=%2Fapps%2Fsnappymail%2F","message":"Call to undefined method MailSo\\Mail\\Message::Subject() in file '/var/www/nextcloud/apps/snappymail/lib/Search/Provider.php' line 109","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"25.0.2.3","exception":{"Exception":"Exception","Message":"Call to undefined method MailSo\\Mail\\Message::Subject() in file '/var/www/nextcloud/apps/snappymail/lib/Search/Provider.php' line 109","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"Error","Message":"Call to undefined method MailSo\\Mail\\Message::Subject()","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Search/SearchComposer.php","line":160,"function":"search","class":"OCA\\SnappyMail\\Search\\Provider","type":"->"},{"file":"/var/www/nextcloud/core/Controller/UnifiedSearchController.php","line":105,"function":"search","class":"OC\\Search\\SearchComposer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"search","class":"OC\\Core\\Controller\\UnifiedSearchController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/snappymail/lib/Search/Provider.php","Line":109},"CustomMessage":"--"}}

Debian 11 / Nextcloud 25.0.2 / PHP 8.0 FPM / SnappyMail 2.24.4

**Comment by the-djmaze** [comment]
@Silberlog wait for next release :wink:

**Comment by Silberlog** [comment]
> @Silberlog wait for next release wink

Ok, thanks !
