### ISSUE TITLE
[Gmail].Folder not visible

### ISSUE THREAD

**Issue by Psychi1** [the-djmaze/snappymail#94]
**Describe the bug**
I'm unable to access folder from Gmail via IMAP. On my Gmail-Account the root folder is named [Gmail] and subsequent folders are mixed german and english. Maybe a duplicate of issue #70 - but unsolved.

**To Reproduce**
1. Go to Folder-Setting
2. Click on Folder (in german "Ordner")
3. See on right panel, the folders are missing. (first picture: rainloop, second und third: snappymail ) 

This is the way how it looks in rainloop - All folders are shown. This is the expected behavior.
![rainloop_issue_github](https://user-images.githubusercontent.com/35874716/119350230-5d88cb00-bc9f-11eb-89a3-92bdbec48656.png)

In Snappymail 2.5.1 the [Gmail] and subfolders are missing:
![snappymail_issue_github](https://user-images.githubusercontent.com/35874716/119350231-5e216180-bc9f-11eb-9335-8529ce5bbdd4.png)

It's not related to the subscribed folders-option.
![snappymail_issue_github2](https://user-images.githubusercontent.com/35874716/119350232-5e216180-bc9f-11eb-9b68-f9065508a630.png)

**Expected behavior**
Look at the first picture. All folders from the [Gmail]-root are shown (red framed). 

**Screenshots**
Look at the "To Reproduce"-section.

**Desktop (please complete the following information):**
 - Browser: Firefox 88.0.1 on Ubuntu 20.04 LTS (all updates applied)
 - SnappyMail Version 2.5.1
 - Rainloop Version 1.15.0

**Additional context**
 - snappymail runs on php 7.4 while rainloop runs on php 7.2

**Comment by the-djmaze** [comment]
Are you sure?
I've fixed this issue long ago and reported to RainLoop because RainLoop couldn't either.
Then i've made a quick patch for RainLoop and they implemented it.

After that, RainLoop made more modifications to this issue and i've implemented those changes.

I did some tests and both RainLoop v1.16 and SnappyMail have no issues here.
See the demo at https://snappymail.eu/demo/

**Comment by Psychi1** [comment]
I'm absolutely sure.  

I recreated the mailbox (1. Delete account from user, 2. Delete domain from admin, 3. clear Cache). However the folders are still missing. 

In the log i found the missing folders (e. g. [Gmail]/Gesendet)
```
[2021-05-28 18:24:40.762][54d2d6cb] IMAP[DATA]: < * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- SPECIAL-USE APPENDLIMIT=35651584\r\n
[2021-05-28 18:24:40.762][54d2d6cb] IMAP[DATA]: < TAG2 OK ************@gmail.com authenticated (Success)\r\n
[2021-05-28 18:24:40.762][54d2d6cb] IMAP[TIME]: 0.084448099136353 (TAG2)
[2021-05-28 18:24:40.762][54d2d6cb] IMAP[DATA]: > TAG3 LSUB "" "*"\r\n
[2021-05-28 18:24:40.787][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren) "/" "Archiv"\r\n
[2021-05-28 18:24:40.787][54d2d6cb] IMAP[DATA]: < * LSUB (\HasChildren) "/" "BLC"\r\n
[2021-05-28 18:24:40.787][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren) "/" "BLC/CESI"\r\n
[2021-05-28 18:24:40.787][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren) "/" "BLC/JHV"\r\n
[2021-05-28 18:24:40.787][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren) "/" "BLC/K&APY-nigswinter"\r\n
[2021-05-28 18:24:40.787][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren) "/" "BLC/Trash"\r\n
[2021-05-28 18:24:40.787][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren) "/" "Drafts"\r\n
[2021-05-28 18:24:40.788][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren) "/" "INBOX"\r\n
[2021-05-28 18:24:40.788][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren) "/" "Junk E-mail"\r\n
[2021-05-28 18:24:40.788][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren) "/" "LVL"\r\n
[2021-05-28 18:24:40.788][54d2d6cb] IMAP[DATA]: < * LSUB (\HasChildren \Noselect) "/" "[Gmail]"\r\n
[2021-05-28 18:24:40.788][54d2d6cb] IMAP[DATA]: < * LSUB (\All \HasNoChildren) "/" "[Gmail]/Alle Nachrichten"\r\n
[2021-05-28 18:24:40.788][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren) "/" "[Gmail]/Drafts"\r\n
[2021-05-28 18:24:40.788][54d2d6cb] IMAP[DATA]: < * LSUB (\Drafts \HasNoChildren) "/" "[Gmail]/Entw&APw-rfe"\r\n
[2021-05-28 18:24:40.788][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren \Sent) "/" "[Gmail]/Gesendet"\r\n
[2021-05-28 18:24:40.788][54d2d6cb] IMAP[DATA]: < * LSUB (\Flagged \HasNoChildren) "/" "[Gmail]/Markiert"\r\n
[2021-05-28 18:24:40.788][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren \Trash) "/" "[Gmail]/Papierkorb"\r\n
[2021-05-28 18:24:40.788][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren) "/" "[Gmail]/Sent objects"\r\n
[2021-05-28 18:24:40.788][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren) "/" "[Gmail]/Trash"\r\n
[2021-05-28 18:24:40.788][54d2d6cb] IMAP[DATA]: < * LSUB (\HasNoChildren \Important) "/" "[Gmail]/Wichtig"\r\n
[2021-05-28 18:24:40.788][54d2d6cb] IMAP[DATA]: < TAG3 OK Success\r\n
```
but they are not displayed at the menue.

![folder menue](https://user-images.githubusercontent.com/35874716/120027522-bfc13300-bff3-11eb-950c-55bdc487fee0.png)

Later in the log, the Folders are missing.
```
2021-05-28 18:24:41.979][3d835620] INFO[DATA]: [DATE:2021-05-28 UTC][RL:2.5.1][PHP:7.4.18][IP:37.201.199.7][PID:25601][nginx/1.20.0][fpm-fcgi]
[2021-05-28 18:24:41.979][3d835620] INFO[DATA]: [APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3]
[2021-05-28 18:24:41.979][3d835620] REQUEST[NOTE]: [POST] https://********/?/Json/&q[]=/0/
[2021-05-28 18:24:41.979][3d835620] JSON[NOTE]: Action: DoFolderInformationMultiply
[2021-05-28 18:24:41.979][3d835620] POST[DATA]: {"Folders":["Archiv","BLC","BLC\/CESI","BLC\/JHV","BLC\/K&APY-nigswinter","BLC\/Trash","Drafts","Junk E-mail","LVL","Sent"],"Action":"FolderInformationMultiply","XToken":"402b80a3b4c7872145de967e73ba503e"}
```

How can I collect more informations for you?

**Comment by Psychi1** [comment]
Hello,

i wiped the hole domain-setup and installed everything new. Now its working perfectly.

**Comment by Psychi1** [comment]
Oh no ... i need to reopen this issue.

Everything was working okay, but as I changed the language to German, the folders get lost - maybe because of an update on imap-folders. After a new try with a blank domain, it still doesn't work.

**Comment by the-djmaze** [comment]
I've reverted the changes so that they are visible again

**Comment by Psychi1** [comment]
hello @the-djmaze,

now it works like a charm. 

![2021-05-31_snappy_working](https://user-images.githubusercontent.com/35874716/120228663-dc57a800-c24b-11eb-8b8d-7783dd580de7.png)

I will close this issue, because it's solved.
